name: Windows 2022

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 600

    steps:
    - name: Download Ngrok Stable
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract Ngrok
      run: Expand-Archive ngrok.zip -DestinationPath ngrok

    - name: Create start.bat
      run: |
        Add-Content start.bat "@echo off"
        Add-Content start.bat "echo ================================"
        Add-Content start.bat "echo       RDP INFORMATION"
        Add-Content start.bat "echo ================================"
        Add-Content start.bat "cd ngrok"
        Add-Content start.bat "ngrok.exe tcp --region ap 3389"
        Add-Content start.bat "pause"

    - name: Create keepalive.ps1
      run: |
        Add-Content keepalive.ps1 "while ($true) { Start-Sleep -Seconds 300 }"

    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - name: Setup Ngrok Authtoken
      run: .\ngrok\ngrok.exe config add-authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Start Ngrok + Show Info
      run: cmd /c start.bat

    - name: Keep Alive
      run: powershell.exe -ExecutionPolicy Bypass -File keepalive.ps1
