name: Windows 2022

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok
      run: |
        Invoke-WebRequest https://downloads.ngrok.com/windows/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Create Required Files (start, loop, wallpaper)
      run: |
        # start.bat
        @'
        @echo off
        echo ======================================
        echo        YOUR WINDOWS RDP IS READY
        echo ======================================
        echo Copy Ngrok IP from GitHub Actions log
        timeout /t 99999
        '@ | Out-File -Encoding ASCII start.bat

        # loop.bat
        @'
        :loop
        timeout /t 60 >nul
        goto loop
        '@ | Out-File -Encoding ASCII loop.bat

        # wallpaper.bat
        @'
        @echo off
        reg add "HKCU\Control Panel\Desktop" /v Wallpaper /t REG_SZ /d "%cd%\wallpaper.png" /f
        RUNDLL32.EXE user32.dll,UpdatePerUserSystemParameters
        '@ | Out-File -Encoding ASCII wallpaper.bat

        # wallpaper.png (new working link)
        Invoke-WebRequest https://raw.githubusercontent.com/2hha/winrdp-wallpaper/main/wallpaper.png -OutFile wallpaper.png

    - name: Extract Ngrok File
      run: Expand-Archive ngrok.zip -DestinationPath ngrok

    - name: Connect to Ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable RDP Access
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy wallpaper.png C:\Users\Public\Desktop\wallpaper.png
        copy wallpaper.bat C:\Users\Public\Desktop\wallpaper.bat

    - name: Open Ngrok Tunnel
      run: Start-Process powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'

    - name: Start RDP Session
      run: cmd /c start.bat

    - name: Keep Workflow Alive
      run: cmd /c loop.bat
