name: Windows 2022 Cloudflared RDP

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 9999

    steps:
    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - name: Download Cloudflared
      run: |
        Invoke-WebRequest https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe -OutFile cloudflared.exe

    - name: Start Cloudflare Tunnel (RDP)
      run: |
        Start-Process powershell -ArgumentList '-NoExit -Command "./cloudflared.exe tunnel --url tcp://localhost:3389"'

    - name: Show Tunnel URL
      run: |
        Start-Sleep -Seconds 8
        Get-Content "$env:USERPROFILE\.cloudflared\*.log"

    - name: Keep Alive
      run: |
        echo "Keeping runner alive..."
        powershell -command "Start-Sleep -Seconds 9999999"
