name: Windows 2022

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok Stable
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract Ngrok
      run: Expand-Archive ngrok.zip -DestinationPath ngrok

    - name: Create start.bat
      run: |
        Add-Content start.bat "@echo off"
        Add-Content start.bat "echo ================================"
        Add-Content start.bat "echo       RDP INFORMATION"
        Add-Content start.bat "echo ================================"
        Add-Content start.bat "ngrok.exe"
        Add-Content start.bat "pause"

    - name: Create loop.bat (Keep alive)
      run: |
        Add-Content loop.bat ":loop"
        Add-Content loop.bat "timeout /t 99999"
        Add-Content loop.bat "goto loop"

    - name: Create wallpaper.bat (Optional)
      run: |
        Add-Content wallpaper.bat "@echo off"
        Add-Content wallpaper.bat "echo Wallpaper applied!"

    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - name: Setup Ngrok Authtoken
      run: .\ngrok\ngrok.exe config add-authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Start Ngrok Tunnel
      run: Start-Process powershell -ArgumentList '-NoExit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'

    - name: Show RDP Info
      run: cmd /c start.bat

    - name: Keep Alive
      run: cmd /c loop.bat
