name: Windows 2022

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 9999

    steps:
    - name: Download tools
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/techies2k/rdp-wallpapers/main/start-2022.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/techies2k/rdp-wallpapers/main/wallpaper.png -OutFile wallpaper.png
        Invoke-WebRequest https://raw.githubusercontent.com/techies2k/rdp-wallpapers/main/wallpaper.bat -OutFile wallpaper.bat
        Invoke-WebRequest https://raw.githubusercontent.com/techies2k/rdp-wallpapers/main/loop.bat -OutFile loop.bat

    - name: Extract Ngrok
      run: Expand-Archive ngrok.zip -DestinationPath ngrok

    - name: Add Ngrok Token
      run: .\ngrok\ngrok.exe config add-authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        copy wallpaper.png C:\Users\Public\Desktop\
        copy wallpaper.bat C:\Users\Public\Desktop\

    - name: Run Ngrok Tunnel
      run: Start-Process powershell -ArgumentList '-NoExit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'

    - name: Show Connection Info
      run: cmd /c start.bat

    - name: Keep Alive
      run: cmd /c loop.bat
